import { CategoryInfo, PriorityInfo, Task } from '../types';

export const CATEGORIES: Record<string, CategoryInfo> = {
  trabalho: {
    id: 'trabalho',
    label: 'Trabalho',
    iconName: 'Briefcase',
    color: 'text-blue-600 dark:text-blue-400',
    bgColor: 'bg-blue-50 dark:bg-blue-950/60',
    borderColor: 'border-blue-200 dark:border-blue-800',
  },
  pessoal: {
    id: 'pessoal',
    label: 'Pessoal',
    iconName: 'User',
    color: 'text-purple-600 dark:text-purple-400',
    bgColor: 'bg-purple-50 dark:bg-purple-950/60',
    borderColor: 'border-purple-200 dark:border-purple-800',
  },
  estudos: {
    id: 'estudos',
    label: 'Estudos',
    iconName: 'GraduationCap',
    color: 'text-amber-600 dark:text-amber-400',
    bgColor: 'bg-amber-50 dark:bg-amber-950/60',
    borderColor: 'border-amber-200 dark:border-amber-800',
  },
  saude: {
    id: 'saude',
    label: 'Saúde',
    iconName: 'HeartPulse',
    color: 'text-emerald-600 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/60',
    borderColor: 'border-emerald-200 dark:border-emerald-800',
  },
  compras: {
    id: 'compras',
    label: 'Compras',
    iconName: 'ShoppingCart',
    color: 'text-pink-600 dark:text-pink-400',
    bgColor: 'bg-pink-50 dark:bg-pink-950/60',
    borderColor: 'border-pink-200 dark:border-pink-800',
  },
  financas: {
    id: 'financas',
    label: 'Finanças',
    iconName: 'DollarSign',
    color: 'text-teal-600 dark:text-teal-400',
    bgColor: 'bg-teal-50 dark:bg-teal-950/60',
    borderColor: 'border-teal-200 dark:border-teal-800',
  },
  outros: {
    id: 'outros',
    label: 'Outros',
    iconName: 'Bookmark',
    color: 'text-slate-600 dark:text-slate-400',
    bgColor: 'bg-slate-50 dark:bg-slate-900',
    borderColor: 'border-slate-200 dark:border-slate-800',
  },
};

export const PRIORITIES: Record<string, PriorityInfo> = {
  baixa: {
    id: 'baixa',
    label: 'Baixa',
    color: 'text-slate-600 dark:text-slate-400',
    badgeBg: 'bg-slate-100 dark:bg-slate-800 border-slate-300 dark:border-slate-700',
    dotColor: 'bg-slate-400',
    rank: 1,
  },
  media: {
    id: 'media',
    label: 'Média',
    color: 'text-blue-700 dark:text-blue-300',
    badgeBg: 'bg-blue-50 dark:bg-blue-950/70 border-blue-200 dark:border-blue-800',
    dotColor: 'bg-blue-500',
    rank: 2,
  },
  alta: {
    id: 'alta',
    label: 'Alta',
    color: 'text-amber-700 dark:text-amber-300',
    badgeBg: 'bg-amber-50 dark:bg-amber-950/70 border-amber-200 dark:border-amber-800',
    dotColor: 'bg-amber-500',
    rank: 3,
  },
  urgente: {
    id: 'urgente',
    label: 'Urgente',
    color: 'text-rose-700 dark:text-rose-300',
    badgeBg: 'bg-rose-50 dark:bg-rose-950/70 border-rose-200 dark:border-rose-800',
    dotColor: 'bg-rose-500 animate-pulse',
    rank: 4,
  },
};

export const INITIAL_DEMO_TASKS: Task[] = [
  {
    id: 'demo-1',
    title: 'Apresentar o projeto de Lista de Tarefas PWA',
    description: 'Verificar interface responsiva, funcionamento mobile e instalação.',
    completed: true,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    priority: 'alta',
    category: 'estudos',
    subtasks: [
      { id: 'sub-1', title: 'Layout responsivo para smartphones', completed: true },
      { id: 'sub-2', title: 'Validação de campos obrigatórios', completed: true },
      { id: 'sub-3', title: 'Configuração PWA com ícone', completed: true },
    ],
    completedAt: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    title: 'Organizar reuniões da semana',
    description: 'Alinhar metas e verificar prazos pendentes com a equipe.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '15:00',
    priority: 'urgente',
    category: 'trabalho',
    subtasks: [
      { id: 'sub-4', title: 'Preparar pauta com 3 tópicos', completed: false },
      { id: 'sub-5', title: 'Enviar convite pelo calendário', completed: true },
    ],
  },
  {
    id: 'demo-3',
    title: 'Comprar frutas e café no mercado',
    description: 'Maçãs, bananas, café em grãos e aveia.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    priority: 'media',
    category: 'compras',
    subtasks: [],
  },
  {
    id: 'demo-4',
    title: 'Caminhada ou exercício por 30 minutos',
    description: 'Manter a constância diária para cuidar da saúde.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    priority: 'baixa',
    category: 'saude',
    subtasks: [],
  },
];
